"""
============================================================
FILE    : hex_to_img.py
PROJECT : FPGA-Based Sobel Edge Detection
PURPOSE : Reads FPGA hardware output (hw_edges.hex) and
          converts it back to an image. Then compares the
          hardware edge map with software edge map and
          generates comparison panel + latency chart.

WHEN TO RUN:
  After Vivado simulation completes and hw_edges.hex exists.
  The testbench (tb_sobel_top.v) writes hw_edges.hex automatically.

HOW TO RUN:
  python software/src/hex_to_img.py

METRICS EXPLAINED:
  MSE (Mean Squared Error):
    Average of (SW_pixel - HW_pixel)^2 across all pixels
    0 = identical outputs, higher = more difference

  PSNR (Peak Signal-to-Noise Ratio):
    10 * log10(255^2 / MSE)
    Higher is better. inf = perfect match
    >30dB is excellent for edge maps

  Pixel Match %:
    Percentage of pixels that are exactly the same (both 0 or both 255)
    100% = perfect match

  Edge IoU (Intersection over Union):
    How much the detected edges overlap between SW and HW
    100% = same edges detected, 0% = completely different edges

OUTPUT (in comparison/results/):
  comparison_imagename.png     - 3-panel: Input | SW edges | HW edges
  latency_chart_imagename.png  - Bar chart: SW vs HW latency + speedup
============================================================
"""

import cv2           # Image reading and writing
import numpy as np   # Array math for metrics
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # Chart generation
import os            # File operations

# Input file paths — all generated by previous steps
SIM_DIR   = os.path.join(os.path.dirname(__file__), '..', '..', 'hardware', 'simulation')
HW_HEX    = os.path.join(SIM_DIR, 'hw_edges.hex')    # Written by Vivado testbench
SW_HEX    = os.path.join(SIM_DIR, 'sw_edges.hex')    # Written by img_to_hex.py
INFO_FILE = os.path.join(SIM_DIR, 'image_info.txt')  # Written by img_to_hex.py

# Output directory for comparison images
OUT_DIR = os.path.join(
    os.path.dirname(__file__), '..', '..', 'comparison', 'results'
)


def read_info():
    """
    Read image_info.txt written by img_to_hex.py.
    Contains: image name, dimensions, SW and HW latency values.
    Returns dict or None if file not found.
    """
    if not os.path.exists(INFO_FILE):
        print(f"[ERROR] {INFO_FILE} not found.")
        print(f"[INFO]  Run img_to_hex.py first.")
        return None
    info = {}
    with open(INFO_FILE) as f:
        for line in f:
            line = line.strip()
            if '=' in line:
                k, v = line.split('=', 1)
                info[k] = v
    return info


def hex_to_array(hex_file, width, height):
    """
    Read hex file and convert to 2D numpy image array.
    Each line in the file = one pixel value in hex.
    Pixels are in raster order: row by row, left to right.

    Args:
        hex_file : Path to .hex file
        width    : Image width in pixels
        height   : Image height in pixels
    Returns:
        numpy array of shape (height, width) dtype uint8
    """
    pixels = []
    x_count = 0
    with open(hex_file) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    # int(line, 16) converts hex string to integer
                    # "ff" → 255, "00" → 0, "c8" → 200
                    pixels.append(int(line, 16))
                except ValueError:
                    # 'xx' = X-state (uninitialized signal in simulation)
                    # Treat as 0 (black pixel) for image reconstruction
                    pixels.append(0)
                    x_count += 1
    if x_count > 0:
        print(f"[WARN]  {x_count} X-state pixels ('{hex_file}') replaced with 0")

    arr = np.array(pixels, dtype=np.uint8)

    # Reshape flat list into 2D image (height rows × width columns)
    arr = arr.reshape(height, width)
    return arr


def compute_metrics(sw, hw):
    """
    Compute quality metrics comparing software vs hardware output.

    Args:
        sw: Software edge map (numpy uint8 array)
        hw: Hardware edge map (numpy uint8 array)
    Returns:
        dict with mse, psnr_db, match_pct, edge_iou
    """
    # Convert to float64 for precise math
    sw_f = sw.astype(np.float64)
    hw_f = hw.astype(np.float64)

    # MSE: mean of squared pixel differences
    mse = np.mean((sw_f - hw_f) ** 2)

    # PSNR: log-scale quality metric (higher = better match)
    # inf means perfect match (MSE=0)
    psnr = 10 * np.log10(255**2 / mse) if mse > 0 else float('inf')

    # Pixel match: what % of pixels are exactly the same
    match_pct = np.sum(sw == hw) / sw.size * 100.0

    # Edge IoU: how much edge pixels overlap (only counts white pixels)
    # True edge pixels where SW and HW both detected edge
    sw_edges = (sw == 255)
    hw_edges = (hw == 255)
    intersection = np.sum(sw_edges & hw_edges)   # Both detected edge
    union        = np.sum(sw_edges | hw_edges)   # Either detected edge
    iou = (intersection / union * 100.0) if union > 0 else 100.0

    return {
        'mse':      round(mse, 4),
        'psnr_db':  round(psnr, 2),
        'match_pct': round(match_pct, 2),
        'edge_iou':  round(iou, 2)
    }


def save_comparison_panel(orig, sw_edges, hw_edges, info, metrics):
    """
    Save 3-panel comparison image:
    [Input Grayscale] [Software Edge Map] [Hardware Edge Map]
    Title shows latency and quality metrics.
    """
    os.makedirs(OUT_DIR, exist_ok=True)
    name     = info['image_name']
    sw_ms    = float(info['sw_latency_ms'])
    hw_ms    = float(info['hw_latency_ms'])
    speedup  = float(info['speedup'])

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(
        f'SW vs HW Edge Detection — {name}\n'
        f'SW: {sw_ms:.3f}ms  |  HW: {hw_ms:.3f}ms  |  '
        f'Speedup: {speedup:.1f}×  |  '
        f'Pixel Match: {metrics["match_pct"]}%  |  '
        f'Edge IoU: {metrics["edge_iou"]}%',
        fontsize=11, fontweight='bold'
    )
    #crop last 4 rows to remove pipeline border artifact
    hw_edges = hw_edges[:60,:]
    sw_edges = sw_edges[:60,:]
    orig = orig[:60,:]
    # Panel 1: Input grayscale image
    axes[0].imshow(orig, cmap='gray')
    axes[0].set_title('Input\n(Grayscale)', fontsize=11)
    axes[0].axis('off')

    # Panel 2: Software output
    axes[1].imshow(sw_edges, cmap='gray')
    axes[1].set_title(
        f'Software Edge Map\n(Python+OpenCV: {sw_ms:.3f} ms)',
        fontsize=11
    )
    axes[1].axis('off')

    # Panel 3: Hardware output
    axes[2].imshow(hw_edges, cmap='gray')
    axes[2].set_title(
        f'Hardware Edge Map\n(FPGA 100MHz: {hw_ms:.3f} ms)',
        fontsize=11
    )
    axes[2].axis('off')

    plt.tight_layout()
    out = os.path.join(OUT_DIR, f'comparison_{name}.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"[SAVED] Comparison panel: {out}")


def save_latency_chart(info, metrics):
    """
    Save bar chart comparing SW vs HW latency.
    Shows speedup factor prominently.
    Goes directly into thesis results section.
    """
    name    = info['image_name']
    sw_ms   = float(info['sw_latency_ms'])
    hw_ms   = float(info['hw_latency_ms'])
    speedup = float(info['speedup'])

    fig, ax = plt.subplots(figsize=(8, 6))

    # Two bars: Software (orange) and Hardware (blue)
    bars = ax.bar(
        ['Software\n(Python + OpenCV)', 'Hardware\n(FPGA @ 100MHz)'],
        [sw_ms, hw_ms],
        color=['#C4860A', '#2C5F8A'],
        edgecolor=['#7A4F00', '#1A3A5C'],
        width=0.5
    )

    # Label each bar with exact latency value
    for bar, val in zip(bars, [sw_ms, hw_ms]):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + sw_ms * 0.02,
            f'{val:.3f} ms',
            ha='center', va='bottom',
            fontsize=13, fontweight='bold'
        )

    # Large speedup label in centre of chart
    ax.text(
        0.5, 0.6,
        f'{speedup:.1f}×\nFaster',
        ha='center', va='center',
        fontsize=22, fontweight='bold',
        color='#1A6B1A',
        transform=ax.transAxes
    )

    ax.set_ylabel('Latency (ms)', fontsize=13)
    ax.set_title(
        f'Latency Comparison — {name}\n'
        f'FPGA achieves {speedup:.1f}× speedup over software',
        fontsize=13, fontweight='bold'
    )
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()

    out = os.path.join(OUT_DIR, f'latency_chart_{name}.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"[SAVED] Latency chart: {out}")


def main():
    """
    Main entry point.
    Reads hw_edges.hex (from Vivado) and sw_edges.hex (from img_to_hex.py)
    Computes quality metrics and saves comparison images.
    """
    os.makedirs(OUT_DIR, exist_ok=True)

    # Read image info
    info = read_info()
    if not info:
        return

    w    = int(info['sim_width'])
    h    = int(info['sim_height'])
    name = info['image_name']

    print(f"\n{'='*55}")
    print(f"  HARDWARE vs SOFTWARE COMPARISON")
    print(f"  Image: {name}  |  Size: {w}x{h}")
    print(f"{'='*55}")

    # Check hardware output exists
    if not os.path.exists(HW_HEX):
        print(f"\n[ERROR] Hardware output not found: {HW_HEX}")
        print(f"[INFO]  Complete these steps first:")
        print(f"  1. Run img_to_hex.py to generate input_pixels.hex")
        print(f"  2. Update tb_sobel_top.v with correct IMG_WIDTH/HEIGHT")
        print(f"  3. Run Vivado simulation: 'run 100us' in Tcl console")
        print(f"  4. Testbench will write hw_edges.hex automatically")
        return

    # Load both edge maps from hex files
    sw_edges = hex_to_array(SW_HEX, w, h)
    hw_edges = hex_to_array(HW_HEX, w, h)

    # Load input grayscale for display
    in_hex = os.path.join(SIM_DIR, 'input_pixels.hex')
    orig   = hex_to_array(in_hex, w, h)

    # Save hardware output as PNG
    hw_png = os.path.join(SIM_DIR, 'hw_edges.png')
    cv2.imwrite(hw_png, hw_edges)
    print(f"[SAVED] HW edge PNG: {hw_png}")

    # Compute quality metrics
    metrics = compute_metrics(sw_edges, hw_edges)

    # Print results
    print(f"\n  QUALITY METRICS (SW vs HW):")
    print(f"  MSE          : {metrics['mse']}"
          f"  (0=identical)")
    print(f"  PSNR         : {metrics['psnr_db']} dB"
          f"  (>30dB = excellent)")
    print(f"  Pixel Match  : {metrics['match_pct']}%")
    print(f"  Edge IoU     : {metrics['edge_iou']}%")

    print(f"\n  LATENCY:")
    print(f"  Software  : {info['sw_latency_ms']} ms")
    print(f"  Hardware  : {info['hw_latency_ms']} ms")
    print(f"  Speedup   : {info['speedup']}x faster")

    # Save comparison outputs
    save_comparison_panel(orig, sw_edges, hw_edges, info, metrics)
    save_latency_chart(info, metrics)

    print(f"\n{'='*55}")
    print(f"  DONE. Check: comparison/results/")
    print(f"{'='*55}")


if __name__ == '__main__':
    main()
